import type { ShowcaseProject } from "@/lib/showcase-types";

export const mockProjects: ShowcaseProject[] = [
  {
    id: "demo-1",
    slug: "jam-ai-copilot",
    title: "Jam AI Copilot",
    summary:
      "A gentle coding copilot that helps community builders turn rough Discord ideas into polished shipping plans and launch checklists.",
    category: "AI",
    tags: ["ai", "community", "planning"],
    stack: ["next.js", "openai", "typescript"],
    projectUrl: "https://example.com/jam-ai-copilot",
    repositoryUrl: "https://github.com/example/jam-ai-copilot",
    submittedBy: "Paul",
    isFeatured: true,
    publishedAt: "2026-03-08T09:30:00.000Z",
  },
  {
    id: "demo-2",
    slug: "guild-garden",
    title: "Guild Garden",
    summary:
      "A soft analytics board for community moderators, tracking momentum, contribution streaks, and the healthiest project threads in one view.",
    category: "Community",
    tags: ["analytics", "community", "moderation"],
    stack: ["supabase", "charts", "react"],
    projectUrl: "https://example.com/guild-garden",
    repositoryUrl: "https://github.com/example/guild-garden",
    submittedBy: "Ananya",
    isFeatured: true,
    publishedAt: "2026-03-06T14:20:00.000Z",
  },
  {
    id: "demo-3",
    slug: "driftframe",
    title: "Driftframe",
    summary:
      "A cinematic portfolio builder for hackathon teams who want to turn a repo, demo, and changelog into a launch-ready project page in minutes.",
    category: "Creative Tools",
    tags: ["design", "portfolio", "launch"],
    stack: ["tailwind", "framer-motion", "vercel"],
    projectUrl: "https://example.com/driftframe",
    repositoryUrl: "https://github.com/example/driftframe",
    submittedBy: "Lena",
    isFeatured: false,
    publishedAt: "2026-03-05T11:05:00.000Z",
  },
  {
    id: "demo-4",
    slug: "signal-stack",
    title: "Signal Stack",
    summary:
      "A lightweight observability kit for Discord-based product communities, surfacing release notes, bug bursts, and feedback spikes without noisy dashboards.",
    category: "Devtools",
    tags: ["observability", "monitoring", "discord"],
    stack: ["next.js", "supabase", "lucide"],
    projectUrl: null,
    repositoryUrl: "https://github.com/example/signal-stack",
    submittedBy: "Mira",
    isFeatured: false,
    publishedAt: "2026-03-03T16:45:00.000Z",
  },
  {
    id: "demo-5",
    slug: "paper-lantern",
    title: "Paper Lantern",
    summary:
      "A calm writing studio for documenting project progress, turning each milestone into a beautifully readable changelog card for collaborators and judges.",
    category: "Productivity",
    tags: ["docs", "writing", "workflow"],
    stack: ["mdx", "supabase", "search"],
    projectUrl: "https://example.com/paper-lantern",
    repositoryUrl: null,
    submittedBy: "Keerthi",
    isFeatured: false,
    publishedAt: "2026-03-02T08:10:00.000Z",
  },
  {
    id: "demo-6",
    slug: "loom-labs",
    title: "Loom Labs",
    summary:
      "A no-drama automation hub that connects Discord project threads to checklists, issue queues, and build updates with a single opinionated workflow.",
    category: "Automation",
    tags: ["automation", "issues", "ops"],
    stack: ["discord", "github", "typescript"],
    projectUrl: "https://example.com/loom-labs",
    repositoryUrl: "https://github.com/example/loom-labs",
    submittedBy: "Rohit",
    isFeatured: true,
    publishedAt: "2026-03-01T10:40:00.000Z",
  },
];
